spring:
  rabbitmq:
    username: rabbit
    password: rabbit12345!
    host: host
    port: 5671
    ssl:
      enabled: true
    listener:
      simple:
        acknowledge-mode: manual

  activemq:
    user: active
    password: active12345!
    broker-url: url

